<?xml version="1.0"?>
<package format="3">
  <name>mobotic_description</name>
  <version>0.1.0</version>
  <description>MoboTerra chassis geometry and preserved wheel-module joint layout.</description>
  <maintainer email="noreply@mobotic.invalid">Mobotic Development Team</maintainer>
  <license>Apache-2.0</license>
  <buildtool_depend>ament_cmake</buildtool_depend>
  <exec_depend>ament_index_python</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>robot_state_publisher</exec_depend>
  <exec_depend>ros2launch</exec_depend>
  <test_depend>ament_cmake_pytest</test_depend>
  <exec_depend>mobotic_config</exec_depend>
  <exec_depend>xacro</exec_depend>
  <export>
    <build_type>ament_cmake</build_type>
  </export>
</package>
